### ISSUE TITLE
Missing data and data discrepancies

### ISSUE THREAD

**Issue by emiliana32** [orbs-network/ton-vote#28]
Hello,
I am analysing the results of some of the TON Foundation's proposals on TON.VOTE and I have found some minor problems. In particular, the [TON Believers Fund](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQAiqphPtZ2jLyzqrcfVrhBZfarghWKpkt0fSfALsqRbofQ7) has no data, even the CSV is empty (it was working last week). Also, in the [TON Tokenomics Optimization](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQCVy5bEWLQZrh5PYb1uP3FSO7xt4Kobyn4T9pGy2c5-i-GS) proposal, the total number of Yes votes displayed on the website is different from the one in the CSV file. Finally, in the [TON Community Proposal to Implement Toncoin Real-Time Burn](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQAx5JjTHpQ_5EeWBAErl4_AWhh_JFBh2UvuTWAeqdbpC0C1) the voting power results calculated from the CSV are slightly different from those shown on TON.VOTE.
Could you please have a look to confirm if there is something wrong?
Thank you

**Comment by amihaz** [comment]
Hi, thanks for letting us know. We will look on these issues and update.

**Comment by amihaz** [comment]
Thanks for reporting this issue, we have deployed a fix.

**Comment by emiliana32** [comment]
Thank you very much for solving the main problem. Now there are other problems.
For example, in the Tokenomics Optimisation proposal, the total number of Yes votes displayed on the website is different from that in the CSV file.
The wallet `EQC_DtMqyeE3sgnqXLSwTxgT4rGBOSHY2M0jpb16AxNhgqPt 20.652826145 17/02/23 17:08:58` does not have a vote, but is counted as Yes.
Furthermore, in both Tokenomics Optimisation and Real-Time Burn the voting power results calculated from the CSV are slightly different from those shown on TON.VOTE.
Tokenomics Optimization
```
CSV - web site
Yes	1,674,041 - 1.67M -> ok
No	147,566 - 147.6K -> ok
Abstain	2,908 - 2.92K -> wrong approximation
Total	1,824,515 - 1.82M -> ok 
```
Real-Time Burn
```
CSV - web site
Yes	365,634 - 365.62K -> wrong approximation
No	3,996 - 3.98K -> wrong approximation
Abstain	2,613 - 2.61K -> ok
Total	372,242 - 372.24K -> ok
```
Finally, in the TON Believers Fund, the problem is the same:
```
CSV - web site
Yes	2,286,387 - 2.29M -> ok
No	10,674 - 10.57K -> wrong approximation
Abstain	1,376 - 1.38K -> ok
Total	2,298,436 - 2.3M -> ok
```
I found a stranger and potentially much worse problem. Sorting the voting power of the wallets in descending order, I found that only the wallet accounts for about 89.39% of the voting power.
`Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx yes 2054274.12644537 22/08/23 09:11:37`
However, that [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) did not contain that amount, about 2 M TON, on the date of the snapshot 17 August 2023 13:00 UTC. 
Can you please resolve the various issues?
Thank you

P.S. If you need my calculations for reference, you can download them [here](https://drive.proton.me/urls/ZHHGVCC1BM#ItYlWzUFKu02).

**Comment by amihaz** [comment]
Are you sure you are not looking on the old CSV? I see different numbers that you are reporting

**Comment by emiliana32** [comment]
> Are you sure you are not looking on the old CSV? I see different numbers that you are reporting

Yes, I can confirm that with the latest version the problem is still present.

**Comment by amihaz** [comment]
Hi @emiliana32 ,

Thanks a lot for all the info.

> For example, in the Tokenomics Optimisation proposal, the total number of Yes votes displayed on the website is different from that in the CSV file.

We use rounding to 2 decimal points when presenting the data on our UI so 1287 turns to 1.29K.

> The wallet EQC_DtMqyeE3sgnqXLSwTxgT4rGBOSHY2M0jpb16AxNhgqPt 20.652826145 17/02/23 17:08:58 does not have a vote, but is counted as Yes.

We do not see this vote counted as Yes, can you share how did you get to this conclusion?

> Furthermore, in both Tokenomics Optimisation and Real-Time Burn the voting power results calculated from the CSV are slightly different from those shown on TON.VOTE.

We indeed had some UI rounding issues all fixes will be released soon.

> I found a stranger and potentially much worse problem. Sorting the voting power of the wallets in descending order, I found that only the wallet accounts for about 89.39% of the voting power.

This was a validator vote, meaning that validators can vote from their operation wallet on ton vote and get the voting power of their staked balance from elector. you can read more about this proposal type [here](https://github.com/orbs-network/ton-vote#validators-vote)

**Comment by emiliana32** [comment]
> We use rounding to 2 decimal points when presenting the data on our UI so 1287 turns to 1.29K

Ok.
> We do not see this vote counted as Yes, can you share how did you get to this conclusion?

According to the website there were 1726 votes (see Recent Votes) while according to the CSV file there should be 1725 plus the wallet `EQC_DtMqyeE3sgnqXLSwTxgT4rGBOSHY2M0jpb16AxNhgqPt`. Also, how is it possible that a wallet voted without expressing a preference?
> We indeed had some UI rounding issues all fixes will be released soon.

Ok.
> This was a validator vote, meaning that validators can vote from their operation wallet on ton vote and get the voting power of their staked balance from elector. you can read more about this proposal type [here](https://github.com/orbs-network/ton-vote#validators-vote)

Since a validator can vote, this should be made clearer both in the proposal and after the vote in the results, since a validator can heavily influence the outcome. In the last TBF proposal, one validator had a total weight of 89.38% and therefore decided for everyone without informing the nominators. The validators should declare their choice before the vote so that the nominators become aware.
I have two more questions:
1. If a wallet with staked coins on a validator votes, its voting power is limited to non stacked coins. Right?
2. Unfortunately, I could not find the [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) of the validator among the [validator list](https://tonwhales.com/staking/stats/validators). Also, the wallet did not contain that amount, about 2 M TON, as of the snapshot date 17 August 2023 13:00 UTC (there are no validators with 2 million coins and there never were).

Thank you

**Comment by amihaz** [comment]
> According to the website there were 1726 votes (see Recent Votes) while according to the CSV file there should be 1725 plus the wallet EQC_DtMqyeE3sgnqXLSwTxgT4rGBOSHY2M0jpb16AxNhgqPt. Also, how is it possible that a wallet voted without expressing a preference?

This wallet voted by sending tx directly to the proposal contract without sending any vote. Our UI present this vote (it will be filter in future versions) but you do not see it on the CSV. bottom line, this vote is invalid and is not counted.

> Since a validator can vote, this should be made clearer both in the proposal and after the vote in the results, since a validator can heavily influence the outcome.

We have a very clear indication in the UI that this is a proposal which validators can vote:

<img width="387" alt="image" src="https://github.com/orbs-network/ton-vote/assets/82806769/6e540dbb-bcab-4455-b34e-912a8a19d5eb">

> The validators should declare their choice before the vote so that the nominators become aware. 

We have no control over the validators which controls the nominators pool. We can try to assist in this task by creating another feature which will assist nominators to in casting their vote to the validator that operating the pool. Do you think this feature will be useful?

> I have two more questions: 
> 1.If a wallet with staked coins on a validator votes, its voting power is limited to non stacked coins. Right?

No. This feature was developed to assist validators in casting their vote without withdrawing the funds from the elector. The validators are responsible for maintaining the network and usually can not cast their vote. On some scenarios (like in the TBF proposal) you want also the validators to participate in the proposal but without withdrawing the funds from electors as it might effect the stability of the network.

> Unfortunately, I could not find the [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) of the validator among the [validator list](https://tonwhales.com/staking/stats/validators). Also, the wallet did not contain that amount, about 2 M TON, as of the snapshot date 17 August 2023 13:00 UTC (there are no validators with 2 million coins and there never were).

Our platform supports single-nominator, nominator pool and simple wallets on this type of proposal. This means that the these wallets delegate their voting power to the controllers. In this example the voting wallet is the controller of the single nominator code and voted with his power.

**Comment by emiliana32** [comment]
>This wallet voted by sending tx directly to the proposal contract without sending any vote. Our UI present this vote (it will be filtered in future versions) but you do not see it on the CSV. bottom line, this vote is invalid and is not counted.

OK, but it is currently in the CSV, line 655.

>We have a very clear indication in the UI that this is a proposal which validators can vote:

You are right, I had not noticed it and it is the first proposal I have seen to use it. However, the [TON Foundation-Community](https://t.me/toncoin/970) did not say anything in its message about this. For what reason? Curious.

> We have no control over the validators which controls the nominators pool. We can try to assist in this task by creating another feature which will assist nominators in casting their vote to the validator that operating the pool. Do you think this feature will be useful?

Of course, this is of paramount importance if the project aims at decentralisation and democracy. Each nominator should be able to decide what to vote for, if this is not possible at least to know what his validator will vote for and then in case he disagrees he could withdraw his wager coins.

> No. This feature was developed to assist validators in casting their vote without withdrawing the funds from the elector. The validators are responsible for maintaining the network and usually can not cast their vote. On some scenarios (like in the TBF proposal) you want also the validators to participate in the proposal but without withdrawing the funds from electors as it might effect the stability of the network.

Perhaps I did not explain myself well. I was referring to a nominator wallet that has some coins staked on a validator and others not staked. In this case, is the voting power of the wallet limited to the non staked coins?

> Our platform supports single-nominator, nominator pool and simple wallets on this type of proposal. This means that the these wallets delegate their voting power to the controllers. In this example the voting wallet is the controller of the single nominator code and voted with his power.

Ia m sorry, but I do not understand. How can we verify where the staked coins come from if the explorer reports an almost empty wallet instead of 2 M coins? Regardless of the type of contract (single-nominator, nominator pool and simple wallets), will there be a way to verify who voted what?

Thank you

**Comment by amihaz** [comment]
> OK, but it is currently in the CSV, line 655. 

Right, the CSV is generated from the same data. Anyway it is not counted and should be filtered.

> However, the [TON Foundation-Community](https://t.me/s/toncoin/970) did not say anything in its message about this. For what reason? Curious. 

I saw some mentions about it in different groups I am not really involved in the PR side.

> Of course, this is of paramount importance if the project aims at decentralisation and democracy. Each nominator should be able to decide what to vote for, if this is not possible at least to know what his/her validator will vote for and then in case he/she disagrees he/she could withdraw his/her staked coins.

Ok, we will be happy to assist here and will add this feature to our roadmap. We will update in the ton.vote support group when it will be ready.

> Perhaps I did not explain myself well. I was referring to a nominator wallet that has some coins staked on a validator and others not staked. In this case, is the voting power of the wallet limited to the non staked coins?

When using nominator pool there are 3 important wallets used. The controller which is controlled by the validator operating the pool, the pool which stakes the coins and the nominators' wallets. Each nominator sends is coins to the pool and the pool stakes the coins. This type of proposal gives the voting power from the pool to the controller. The nominators wallets coins are counted from the pool side only.

> I am sorry, but I do not understand. How can we verify where the staked coins come from if the explorer reports an almost empty wallet instead of 2 M coins? Regardless of the type of contract (single-nominator, nominator pool and simple wallets), will there be a way to verify who voted what?

This requires understanding of the elector code, nominator-pool, single nominator (which are all open source). In general, in every validation period you stake some coins and can only withdraw them in the middle of the next validation period so for example you stake some funds 9 hours before the validation period starts (when election period begins) and can only withdraw them 9 hours after the end of the next validation period which is approx 18 hours so your funds are inaccessible for 36 hours. Bottom line when you see max stake of 900K TONs, it usually means that the validator used 1.8M TONs in 2 cycles as he wants to maximize its APR.

**Comment by emiliana32** [comment]
> Right, the CSV is generated from the same data. Anyway it is not counted and should be filtered.

I agree, it should be removed from both.

> Ok, we will be happy to assist here and will add this feature to our roadmap. We will update in the ton.vote support group when it will be ready.

Great! Thank you

> When using nominator pool there are 3 important wallets used. The controller which is controlled by the validator operating the pool, the pool which stakes the coins and the nominators' wallets. Each nominator sends his coins to the pool and the pool stakes the coins. This type of proposal gives the voting power from the pool to the controller. The nominators wallets coins are counted from the pool side only.

Ok. So this should be clarified. Once a nominator has placed his coins in a validator through a pool, he loses his voting power for those coins. This part should and can be fixed from the previous point.
 
> This requires understanding of the elector code, nominator-pool, single nominator (which are all open source). In general, in every validation period you stake some coins and can only withdraw them in the middle of the next validation period so for example you stake some funds 9 hours before the validation period starts (when election period begins) and can only withdraw them 9 hours after the end of the next validation period which is approx 18 hours so your funds are inaccessible for 36 hours. Bottom line when you see max stake of 900K TONs, it usually means that the validator used 1.8M TONs in 2 cycles as he wants to maximize its APR.

I agree. Maybe with enough time I could analyze each contract, but how many people can do it? Since TON aims at mass adoption, the voting procedure should be as simple as possible to allow everyone to participate.
Yes, I more or less know how a validation works and its [requirements](https://github.com/ton-blockchain/mytonctrl/blob/master/docs/en/nominator-pool.md). However, this means that the actual number of validators [here](https://tonwhales.com/staking/stats/validators) could be at least half of the total number shown. I hope that the update of Elector and Config in the roadmap for Q3 (previously it was for Q2) will improve decentralization and clarity.
Back to the topic of discussion. According to ton.vote data provided by CSV, the first proposal had a supermajority in terms of voting power of 13 wallets out of a total of 1725, the second 10 out of 800 and the third 1 out of 264. For this reason we need a way to verify the actual validator stake taking into account the various wallets. Since in the last case the wallet of the validator according to ton.vote contained 2 M coins while according to the explorer it did not. Without clarity, it seems an easy way to hide voting intentions.

**Comment by emiliana32** [comment]
> According to the website there were 1726 votes (see Recent Votes) while according to the CSV file there should be 1725 plus the wallet EQC_DtMqyeE3sgnqXLSwTxgT4rGBOSHY2M0jpb16AxNhgqPt. Also, how is it possible that a wallet voted without expressing a preference?

Hello, after almost two months the problem has not been solved.
